services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Jwtools2\:
    resource: '../Classes/*'

  # Called by makeInstance in getCallableFromTarget of Dispatcher
  JWeiland\Jwtools2\Controller\Ajax\SysFileController:
    public: true

  JWeiland\Jwtools2\Command\CacheQueryCommand:
    tags:
    - name: 'console.command'
      command: 'jwtools2:cacheQuery'
      schedulable: false
  JWeiland\Jwtools2\Command\ConvertPlainPasswordToHashCommand:
    tags:
    - name: 'console.command'
      command: 'jwtools2:convertpasswords'
      schedulable: false
  JWeiland\Jwtools2\Command\StatusReportCommand:
    arguments:
      - '@TYPO3\CMS\Scheduler\Domain\Repository\SchedulerTaskRepository'
    tags:
    - name: 'console.command'
      command: 'jwtools2:statusreport'
      schedulable: false

  # Called by makeInstance in start() of ContentObjectRenderer
  JWeiland\Jwtools2\Hooks\InitializeStdWrap:
    public: true

  # Element Browser should be registered with tags `recordlist.elementbrowser`
  JWeiland\Jwtools2\Backend\Browser\FileBrowser:
    tags:
      - name: recordlist.elementbrowser

  JWeiland\Jwtools2\LinkHandler\FileLinkHandler:
    public: true

  JWeiland\Jwtools2\LinkHandler\FolderLinkHandler:
    public: true

  # Event Listeners
  JWeiland\Jwtools2\EventListener\ReduceCategoryTreeToPageTree:
    tags:
    - name: event.listener
      event: TYPO3\CMS\Core\Tree\Event\ModifyTreeDataEvent

  JWeiland\Jwtools2\EventListener\IndexServiceEventListener:
    tags:
      - name: event.listener
        identifier: 'jwtools2.events.beforeItemIsIndexedEvent'
        event: ApacheSolrForTypo3\Solr\Event\Indexing\BeforeItemIsIndexedEvent

  JWeiland\Jwtools2\EventListener\IsFileSelectableEventListener:
    tags:
      - name: event.listener
        identifier: 'jwtools2.events.isFileSelectableEvent'
        event: TYPO3\CMS\Backend\ElementBrowser\Event\IsFileSelectableEvent

  # Backend Context Menu Provider
  JWeiland\Jwtools2\ContextMenu\ItemProviders\UpdateFileMetaDataProvider:
      tags:
      - name: backend.contextmenu.itemprovider
        identifier: 'jwtools2.contextmenu.itemproviders.updatefilemetadata'
